version: "3.9"
services:
  user-svc-test:
    image: maven:3.9-eclipse-temurin-21
    working_dir: /app
    volumes:
      - ./user-svc:/app
      - maven-cache:/root/.m2
    command: mvn test -q
    environment:
      MAVEN_OPTS: "-Xmx512m"

  product-svc-test:
    image: maven:3.9-eclipse-temurin-21
    working_dir: /app
    volumes:
      - ./product-svc:/app
      - maven-cache:/root/.m2
    command: mvn test -q
    environment:
      MAVEN_OPTS: "-Xmx512m"

  order-svc-test:
    image: maven:3.9-eclipse-temurin-21
    working_dir: /app
    volumes:
      - ./order-svc:/app
      - maven-cache:/root/.m2
    command: mvn test -q
    environment:
      MAVEN_OPTS: "-Xmx512m"

volumes:
  maven-cache:
